### ISSUE TITLE
NewTickets: implement component

### ISSUE THREAD

**Issue by Seerden** [Seerden/trade#29]
### Description:
I'm currently implementing a very minimally viable version of the `NewTickets` component in #16, but there will be a bunch of leftover work to do after that PR, since it shouldn't be a priority to get every task in there finished right away. Keep this issue open to track the progress on those tasks.

### To-do:
- [ ] add unit tests for functionality and components
### NewTickets component:
- [ ] make the component and all subcomponents responsive
- add onSubmit functionality:
  - [ ] add client-side responsive messages ('no valid tickets provided', 'submitting the following tickets: ...', etc.)
- [x] allow deleting individual tickets. Figure out a way to elegantly display 'delete' button, since we don't want to clutter the UI
- [ ] optionally show text input for datetime (JS/dayjs date parsing is clever enough that it should work reliably enough)
- [ ] change placeholder behavior:
  - [ ] only show placeholder in the following cases:
    1. ticket is being hovered or focused
    2. one of the ticket's input fields is active
- ... there's probably more

**Comment by Seerden** [comment]
Working on refining UX and finalizing functionality in #46 .
